"""rename room.price to price_per_night, add original_price

Revision ID: 050871f2e5bc
Revises: 53b4d4b91081
Create Date: 2026-06-04 11:03:28.002750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050871f2e5bc'
down_revision: Union[str, Sequence[str], None] = '53b4d4b91081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price_per_night', sa.Float(), nullable=True))
    op.add_column('rooms', sa.Column('original_price', sa.Float(), nullable=True))
    op.drop_column('rooms', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'original_price')
    op.drop_column('rooms', 'price_per_night')
    # ### end Alembic commands ###
