"""create initial tables

Revision ID: 53b4d4b91081
Revises: 
Create Date: 2026-06-04 09:50:02.316812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b4d4b91081'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('accommodation_type', sa.String(length=100), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('is_luxury', sa.Boolean(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('amenity_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('useful_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_notes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('suitable_for', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('reviews_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('amenities_general', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('amenities_leisure', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('amenities_dining', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Float(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'title')
    )
    op.create_table('nearby_places',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'name')
    )
    op.create_table('rooms',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('room_size', sa.String(length=50), nullable=True),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('bed_type', sa.String(length=255), nullable=True),
    sa.Column('room_view', sa.String(length=100), nullable=True),
    sa.Column('room_amenities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'room_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('nearby_places')
    op.drop_table('activities')
    op.drop_table('hotels')
    # ### end Alembic commands ###
